add a parser option to validate oneofs (#236)
* add a parser option to validate oneofs

The exception looks like:
```
scalapb.json4s.JsonFormatException: Overlapping keys in oneof: primitive, wrapper
```

* code review

* fail on overlapping oneof fields by default
* update names
 * use 'field' instead of 'key' for consistency
 * use 'isIgnoringOverlappingOneofFields' and 'ignoringOverlappingOneofFields' for consistency